name: Deploy GoFiber to ACI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group and ACR
        run: |
          az group create --name ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }}
          az acr create --name ${{ secrets.ACR_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --sku Basic --admin-enabled true

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/gofiberapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/gofiberapp:latest

      - name: Deploy to ACI
        run: |
          az container create \
            --name gofiberaci \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/gofiberapp:latest \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username $(az acr credential show --name ${{ secrets.ACR_NAME }} --query username -o tsv) \
            --registry-password $(az acr credential show --name ${{ secrets.ACR_NAME }} --query passwords[0].value -o tsv) \
            --ports 80 \
            --cpu 1 --memory 1.5 \
            --location ${{ secrets.LOCATION }} \
            --restart-policy Never

      - name: Reminder
        run: echo "⚠️ Vergeet niet je ACI handmatig te verwijderen in Azure Portal of via CLI om kosten te besparen."
